"""empty message

Revision ID: 15f9ed9a9d13
Revises: 34eeeb3054e2
Create Date: 2018-05-06 16:14:27.107479

"""

# revision identifiers, used by Alembic.
revision = '15f9ed9a9d13'
down_revision = '34eeeb3054e2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'deactivated_at')
    # ### end Alembic commands ###
