"""person model created

Revision ID: fde99be08182
Revises: b356f6ae9969
Create Date: 2019-06-22 13:12:40.616862

"""

# revision identifiers, used by Alembic.
revision = 'fde99be08182'
down_revision = 'b356f6ae9969'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('customer_code', sa.String(length=15), nullable=True),
    sa.Column('national_id', sa.String(length=12), nullable=True),
    sa.Column('name', sa.Unicode(length=40), nullable=True),
    sa.Column('family', sa.Unicode(length=60), nullable=True),
    sa.Column('mobile', sa.String(length=13), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###
