env:
  global:
    - COMMIT_AUTHOR_EMAIL: vahid.mardani@gmail.com
language: python
dist: xenial
python: "3.6"
branches:
  only:
  - master
  - develop
  - nightly
  - /^v([1-9]\d*!)?(0|[1-9]\d*)(\.(0|[1-9]\d*))*((a|b|rc)(0|[1-9]\d*))?(\.post(0|[1-9]\d*))?(\.dev(0|[1-9]\d*))?$/
  - iso8583
addons:
  apt:
    sources:
      - precise-pgdg-9.5
    packages:
      - postgresql-9.5
      - postgresql-contrib-9.5
      - libpq-dev
  postgresql: 9.5

services:
  - redis-server

install: ./scripts/travis-install.sh
script: py.test --cov=wolf wolf/tests
after_success: 
  - coveralls
  - ./scripts/travis-upload-wiki.sh
